version: "3.10.3.{build}"

image: Visual Studio 2019
configuration: Release

init:
- ps: git config --global core.autocrlf true

before_build:
- echo /restore /bl >> msbuild.rsp

build:
  verbosity: minimal

artifacts:
  - path: '\GitDiffMargin.Extension\bin\Release\net46\GitDiffMargin.vsix'
    name: build
  - path: '\msbuild.binlog'
    name: build log
